server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Извлекаем имя контейнера
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Извлекаем название сервиса из Docker Compose
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      # Оставляем только логи микросервисов
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: '.*-service|notification-service'
        action: keep
      # Удаляем все служебные метки, оставляем только нужные
      - action: labeldrop
        regex: '__meta_docker.*|__.*'
